#!/bin/sh

black --diff --check train.py test_audionet.py
# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Code is not formatted correctly."
 exit 1
fi 

nosetests

if [ $? -ne 0 ]; then
 echo "Tests must pass before committing."
 exit 1
fi 